# Generated by Django 4.0 on 2021-12-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pasajero'),
        ),
    ]
