# Generated by Django 4.0 on 2021-12-29 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pasajero_apellido_alter_pasajero_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ciudad',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='pais',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
    ]
